### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by BastienLQ** [SecuredText/SecuredText#10]
Should we add a chat room dedicated to SecuredText? That would be a way to discuss with potential contributors and enthusiastic users.

We could use one of these:
* Gitter: free for public rooms
 * pros: GitHub integration
 * cons: only a web interface
* Jabber chat room: free and can be hosted on @Nuolezio (a non-profit organisation)
 * pros: available through any interface we want (XMPP, web chat, even IRC)
 * cons: no GitHub integration

**Comment by pR0Ps** [comment]
I like the idea of having a chat room.

Some other options:

- IRC channel (#SecuredText on Freenode for example)
    - Pros: nothing to set up, no sign-in, can use [webchat](http://webchat.freenode.net/?channels=SecuredText)
    - Cons: IRC is unfamiliar to some, no GitHub integration
- [Slack](https://slack.com/)
    - Pros: Github integration, IRC integration, free for unlimited people
    - Cons: Have to sign up to use it (no casual drop-ins)

I would personally vote for the IRC channel just because it's got the least number of steps to join (click a link, enter a name, hit enter) and it's a pretty standard support mechanism, but really, any of the options are fine.
